### ISSUE TITLE
Discrepancy between Node v10.15 and v10.16

### ISSUE THREAD

**Issue by ElRaptorus** [bcoe/c8#138]
* **Version**: 5.0.1
* **Platform**:
Mac OS Mojave 10.14.6
Node Versions: 10.15 and 10.16
mocha: v6.2.0
ts-mocha: v6.0.0

Greetings,
I've recently started to write unit tests for one of our projects, using mocha, and I've noticed that the reports generated by c8 show some discrepancies, when switching between Node v10.15 and v10.16.

Using Node v10.15:
![Bildschirmfoto 2019-09-02 um 13 20 44](https://user-images.githubusercontent.com/15343316/64111258-8444f680-cd84-11e9-825f-26bb80425eeb.png)

Using Node v10.16:
![Bildschirmfoto 2019-09-02 um 13 20 31](https://user-images.githubusercontent.com/15343316/64111257-8444f680-cd84-11e9-8a08-ac4ab95df948.png)

I noticed that the `Uncovered lines` section in particular shows very different results.
In both cases I used `c8@5.0.1`.

I could probably live with the 0.05% difference in the `statements` and `lines` sections (for now, at least), but an almost 18% difference for `branch` is rather huge. 

So the question is:
How can I tell which one of these reports is more accurate?

Here are the full coverage logs:
[v10.15_coverage.txt](https://github.com/bcoe/c8/files/3565790/v10.15_coverage.txt)
[v10.16_coverage.txt](https://github.com/bcoe/c8/files/3565791/v10.16_coverage.txt)

Thanks in advance for any help!

**Comment by bcoe** [comment]
@ElRaptorus would you be able to provide a repository that demonstrates this discrepancy? Even if it's a small toy repository this helps with debugging.

**Comment by ElRaptorus** [comment]
> @ElRaptorus would you be able to provide a repository that demonstrates this discrepancy? Even if it's a small toy repository this helps with debugging.

I have set up a repository that contains some the tests we had at the time I reported this issue, as well as a basic code implementation that these tests are supposed to cover.

https://github.com/process-engine/c8_debugging

Let me know, if you need anything else.

Thanks!

**Comment by bcoe** [comment]
@ElRaptorus thank you, I'll take a look as soon as possible.

**Comment by bcoe** [comment]
@ElRaptorus the root problem is `ts-mocha`. `v8` can only see the source in memory, which is the compiled TypeScript, however `c8` can only see the files on disk, which are the uncompiled TypeScript (the same problem exists for `ts-node`, `babel-run`, etc).

There's a PR in the work on Node.js to address this issue: https://github.com/nodejs/node/pull/28960

**Comment by ElRaptorus** [comment]
> @ElRaptorus the root problem is `ts-mocha`. `v8` can only see the source in memory, which is the compiled TypeScript, however `c8` can only see the files on disk, which are the uncompiled TypeScript (the same problem exists for `ts-node`, `babel-run`, etc).
> 
> There's a PR in the work on Node.js to address this issue: [nodejs/node#28960](https://github.com/nodejs/node/pull/28960)

I see. 
Then I guess we'll revisit this issue, when that PR is finished.

Thank you for your efforts!

**Comment by bcoe** [comment]
Hey @ElRaptorus, I've tested on newer versions of Node.js, and now that we support source-maps behavior seems correct:

## Node 12+ and c8 6+

👇 the correct parts of the codebase are labeled as covered/uncovered.

<img width="780" alt="correct-lines-covered" src="https://user-images.githubusercontent.com/194609/69906870-160dd100-137f-11ea-9665-32263f74a687.png">

## Node <12 c8 < 6

👇 random parts of the codebase are highlighted, because of a lack of source-map information.

<img width="888" alt="random" src="https://user-images.githubusercontent.com/194609/69906876-3c337100-137f-11ea-9311-37b73c733619.png">

---

The missing source-map information would have been what was creating your highly variable coverage results.

Going forwards, [I recommend doing something like we've done with yargs](https://github.com/yargs/yargs/blob/master/.travis.yml#L18), where you only run coverage for the newest version of Node.js (I think for most folks, this is a sufficient window into the state of the project).

**Comment by ElRaptorus** [comment]
@bcoe Hi, 
I tried this with Node v12 as well and all looks good. Thanks for the effort!
