### ISSUE TITLE
Feature Request: Significance detection

### ISSUE THREAD

**Issue by coreyfarrell** [bcoe/c8#75]
c8 currently does not detect significant / insignificant lines.  Some examples are lines that only contain:
* hashbang
* white-space
* comments
* block closing brackets
* closing parenthesis
* semi-colon / comma

The inclusion of these lines in results artificially inflates coverage percentages.  Silly example for demo purposes:
```js
#!/usr/bin/env node
/*
 * This file has a large comment.
 * This file has a large comment.
 * This file has a large comment.
 * This file has a large comment.
 * This file has a large comment.
 * This file has a large comment.
 * This file has a large comment.
 * This file has a large comment.
 */
if (false) {
  console.log('This is not hit');
  console.log('Neither is this');
}
```
c8 reports 80% of the lines covered (green), nyc reports 33% (red).

**Comment by bcoe** [comment]
@coreyfarrell the latest version of `c8` (PR currently open) does support shebangs... some of these other topics I think, in some cases:

1. are conversations worth having with the folks on V8, if we think they're worth fixing, or.
2. are just differences in how coverage will work in c8 vs., nyc; I'm not that eager to try to get c8 to have 100% feature parity with Istanbul, if it requires two many hacks and band aids on top of the coverage being emitted by V8.

**Comment by bcoe** [comment]
@coreyfarrell this is issue a bit too broad:

* positions of closing parenthesis, commas, semi-colons, are related to how V8 represents coverage position; in some cases I'd argue it's just a difference in how data is represented vs., Istanbul, in other cases it might be legitimate bugs we could open in V8.
* comments are not represented as blocks by the V8 interpreter, so would need to be handled by v8-to-istanbul, or we'd need to strike up a conversation with the V8 team.
* whitespace is a separate issue, would need to see some examples; might either be fixed in V8 or v8-to-istanbul (or not fixed, depending on the situation).
